@echo off
set HOME=c:\gz-ws
set SDF_PATH=c:\gz-ws\sdformat\1.6
set GAZEBO_MASTER_URI=http://localhost:11345
set GAZEBO_MODEL_DATABASE_URI=http://models.gazebosim.org
set GAZEBO_RESOURCE_PATH=c:\gz-ws\share\gazebo-10
set GAZEBO_PLUGIN_PATH=c:\gz-ws\lib\gazebo-10\plugins
set GAZEBO_MODEL_PATH=c:\gz-ws\share\gazebo-10\models
set OGRE_RESOURCE_PATH=c:\gz-ws\bin\Release
set PATH=c:\gz-ws\bin;c:\gz-ws\lib;c:\gz-ws\bin;c:\gz-ws\bin\Release;
